insert into Brand values('Apple')
insert into Brand values('Samsung')
insert into Brand values('Huawei')
insert into Brand values('Xiaomi')
insert into Brand values('Lenovo')
insert into Brand values('Asus')
insert into Brand values('Dell')
insert into Brand values('Google Pixel')
insert into Brand values('Acer')
insert into Brand values('Hp')
insert into Brand values('Msi')
insert into Brand values('Aqua')
insert into Brand values('Toshiba')
insert into Brand values('LG')
go
insert into Category values('Computer')
insert into Category values('Smart Phone')
insert into Category values('Television')
insert into Category values('Fridge')
insert into Category values('Washing machine')
insert into Category values('Air conditioner')
insert into Category values('Other accessories')
go
insert into Products values('P01',' Lenovo Legion Y7000P 2024','Acer Nitro 5 Tiger is a laptop with a super powerful configuration with the latest Intel Core i7-12650H Gen 12 CPU processor and GeForce RTX 4050 discrete card. A land for gamers, right? Right now, we will find out what the Nitro 5 has to offer.',15,30690000,'Mt_1.jpg',1,5)
insert into Products values('P02',' Acer Nitro 5 AN515-58','Acer Nitro 5 Tiger is a laptop with a super powerful configuration with the latest Intel Core i7-12650H Gen 12 CPU processor and GeForce RTX 4050 discrete card. A land for gamers, right? Right now, we will find out what the Nitro 5 has to offer.',10,21690000,'Mt_1.jpg',1,9)
